
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 MasterMap1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 MasterMap2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 MasterMap3 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 MasterMap4 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS8 MasterMap5 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS8 MasterMap6 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS8 MasterMap7 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS8 MasterMap8 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS8 MasterMap9 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS32 MasterMap10 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 MasterMap11 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER16 MasterMap12 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER16 MasterMap13 = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS32 Communications_Parameters_SYNC_COB_ID = 0x80;		/* Mapped at index 0x2060, subindex 0x01 */
UNS32 Communications_Parameters_Communication_Cycle_Period = 0x3D0900;		/* Mapped at index 0x2060, subindex 0x02 */
UNS16 Communications_Parameters_Guard_Time = 0x0;		/* Mapped at index 0x2060, subindex 0x03 */
UNS8 Communications_Parameters_Lift_Tiem_Factor = 0x0;		/* Mapped at index 0x2060, subindex 0x04 */
UNS32 Communications_Parameters_Emergency_COB_ID = 0x80;		/* Mapped at index 0x2060, subindex 0x05 */
UNS32 Communications_Parameters_Consumer_Heartbeat_Time = 0x2710;		/* Mapped at index 0x2060, subindex 0x06 */
UNS16 Communications_Parameters_Producer_Heartbeat_Time = 0x1388;		/* Mapped at index 0x2060, subindex 0x07 */
UNS8 Communications_Parameters_Communication_Error = 0x0;		/* Mapped at index 0x2060, subindex 0x08 */
UNS32 Recive_PDO_Parameters_RPDO1_COB_ID = 0x200;		/* Mapped at index 0x2070, subindex 0x01 */
UNS8 Recive_PDO_Parameters_RPDO1_Transmission_Type = 0x0;		/* Mapped at index 0x2070, subindex 0x02 */
UNS8 Recive_PDO_Parameters_PRDO1_Mapping_Number = 0x3;		/* Mapped at index 0x2070, subindex 0x03 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_04 = 0x0;		/* Mapped at index 0x2070, subindex 0x04 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_05 = 0x0;		/* Mapped at index 0x2070, subindex 0x05 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_06 = 0x0;		/* Mapped at index 0x2070, subindex 0x06 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_07 = 0x0;		/* Mapped at index 0x2070, subindex 0x07 */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_1 = 0x20000020;		/* Mapped at index 0x2070, subindex 0x08 */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_2 = 0x20010010;		/* Mapped at index 0x2070, subindex 0x09 */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_3 = 0x20020010;		/* Mapped at index 0x2070, subindex 0x0A */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_4 = 0x0;		/* Mapped at index 0x2070, subindex 0x0B */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_5 = 0x0;		/* Mapped at index 0x2070, subindex 0x0C */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_6 = 0x0;		/* Mapped at index 0x2070, subindex 0x0D */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_7 = 0x0;		/* Mapped at index 0x2070, subindex 0x0E */
UNS32 Recive_PDO_Parameters_RPDO1_Mapping_8 = 0x0;		/* Mapped at index 0x2070, subindex 0x0F */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_10 = 0x0;		/* Mapped at index 0x2070, subindex 0x10 */
UNS32 Recive_PDO_Parameters_RPDO2_COB_ID = 0x300;		/* Mapped at index 0x2070, subindex 0x11 */
UNS8 Recive_PDO_Parameters_RPDO2_Transmission_Type = 0x0;		/* Mapped at index 0x2070, subindex 0x12 */
UNS8 Recive_PDO_Parameters_PRDO2_Mapping_Number = 0x0;		/* Mapped at index 0x2070, subindex 0x13 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_14 = 0x0;		/* Mapped at index 0x2070, subindex 0x14 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_15 = 0x0;		/* Mapped at index 0x2070, subindex 0x15 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_16 = 0x0;		/* Mapped at index 0x2070, subindex 0x16 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_17 = 0x0;		/* Mapped at index 0x2070, subindex 0x17 */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_1 = 0x0;		/* Mapped at index 0x2070, subindex 0x18 */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_2 = 0x0;		/* Mapped at index 0x2070, subindex 0x19 */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_3 = 0x0;		/* Mapped at index 0x2070, subindex 0x1A */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_4 = 0x0;		/* Mapped at index 0x2070, subindex 0x1B */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_5 = 0x0;		/* Mapped at index 0x2070, subindex 0x1C */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_6 = 0x0;		/* Mapped at index 0x2070, subindex 0x1D */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_7 = 0x0;		/* Mapped at index 0x2070, subindex 0x1E */
UNS32 Recive_PDO_Parameters_RPDO2_Mapping_8 = 0x0;		/* Mapped at index 0x2070, subindex 0x1F */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_20 = 0x0;		/* Mapped at index 0x2070, subindex 0x20 */
UNS32 Recive_PDO_Parameters_RPDO3_COB_ID = 0x80000400;		/* Mapped at index 0x2070, subindex 0x21 */
UNS8 Recive_PDO_Parameters_RPDO3_Transmission_Type = 0x0;		/* Mapped at index 0x2070, subindex 0x22 */
UNS8 Recive_PDO_Parameters_PRDO3_Mapping_Number = 0x0;		/* Mapped at index 0x2070, subindex 0x23 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_24 = 0x0;		/* Mapped at index 0x2070, subindex 0x24 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_25 = 0x0;		/* Mapped at index 0x2070, subindex 0x25 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_26 = 0x0;		/* Mapped at index 0x2070, subindex 0x26 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_27 = 0x0;		/* Mapped at index 0x2070, subindex 0x27 */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_1 = 0x0;		/* Mapped at index 0x2070, subindex 0x28 */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_2 = 0x0;		/* Mapped at index 0x2070, subindex 0x29 */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_3 = 0x0;		/* Mapped at index 0x2070, subindex 0x2A */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_4 = 0x0;		/* Mapped at index 0x2070, subindex 0x2B */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_5 = 0x0;		/* Mapped at index 0x2070, subindex 0x2C */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_6 = 0x0;		/* Mapped at index 0x2070, subindex 0x2D */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_7 = 0x0;		/* Mapped at index 0x2070, subindex 0x2E */
UNS32 Recive_PDO_Parameters_RPDO3_Mapping_8 = 0x0;		/* Mapped at index 0x2070, subindex 0x2F */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_30 = 0x0;		/* Mapped at index 0x2070, subindex 0x30 */
UNS32 Recive_PDO_Parameters_RPDO4_COB_ID = 0x80000500;		/* Mapped at index 0x2070, subindex 0x31 */
UNS8 Recive_PDO_Parameters_RPDO4_Transmission_Type = 0x0;		/* Mapped at index 0x2070, subindex 0x32 */
UNS8 Recive_PDO_Parameters_PRDO4_Mapping_Number = 0x0;		/* Mapped at index 0x2070, subindex 0x33 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_34 = 0x0;		/* Mapped at index 0x2070, subindex 0x34 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_35 = 0x0;		/* Mapped at index 0x2070, subindex 0x35 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_36 = 0x0;		/* Mapped at index 0x2070, subindex 0x36 */
UNS8 Recive_PDO_Parameters_Compatibility_Entry_37 = 0x0;		/* Mapped at index 0x2070, subindex 0x37 */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_1 = 0x0;		/* Mapped at index 0x2070, subindex 0x38 */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_2 = 0x0;		/* Mapped at index 0x2070, subindex 0x39 */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_3 = 0x0;		/* Mapped at index 0x2070, subindex 0x3A */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_4 = 0x0;		/* Mapped at index 0x2070, subindex 0x3B */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_5 = 0x0;		/* Mapped at index 0x2070, subindex 0x3C */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_6 = 0x0;		/* Mapped at index 0x2070, subindex 0x3D */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_7 = 0x0;		/* Mapped at index 0x2070, subindex 0x3E */
UNS32 Recive_PDO_Parameters_RPDO4_Mapping_8 = 0x0;		/* Mapped at index 0x2070, subindex 0x3F */
UNS32 Transmit_PDO_Parameters_TPDO1_COB_ID = 0x180;		/* Mapped at index 0x2080, subindex 0x01 */
UNS8 Transmit_PDO_Parameters_TPDO1_Transmission_Type = 0x0;		/* Mapped at index 0x2080, subindex 0x02 */
UNS32 Transmit_PDO_Parameters_TPDO1_Inhibit_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x03 */
UNS16 Transmit_PDO_Parameters_TPDO1_Event_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x04 */
UNS8 Transmit_PDO_Parameters_TRDO1_Mapping_Number = 0x0;		/* Mapped at index 0x2080, subindex 0x05 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_06 = 0x0;		/* Mapped at index 0x2080, subindex 0x06 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_07 = 0x0;		/* Mapped at index 0x2080, subindex 0x07 */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_1 = 0x0;		/* Mapped at index 0x2080, subindex 0x08 */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_2 = 0x0;		/* Mapped at index 0x2080, subindex 0x09 */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_3 = 0x0;		/* Mapped at index 0x2080, subindex 0x0A */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_4 = 0x0;		/* Mapped at index 0x2080, subindex 0x0B */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_5 = 0x0;		/* Mapped at index 0x2080, subindex 0x0C */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_6 = 0x0;		/* Mapped at index 0x2080, subindex 0x0D */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_7 = 0x0;		/* Mapped at index 0x2080, subindex 0x0E */
UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_8 = 0x0;		/* Mapped at index 0x2080, subindex 0x0F */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_10 = 0x0;		/* Mapped at index 0x2080, subindex 0x10 */
UNS32 Transmit_PDO_Parameters_TPDO2_COB_ID = 0x280;		/* Mapped at index 0x2080, subindex 0x11 */
UNS8 Transmit_PDO_Parameters_TPDO2_Transmission_Type = 0x0;		/* Mapped at index 0x2080, subindex 0x12 */
UNS32 Transmit_PDO_Parameters_TPDO2_Inhibit_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x13 */
UNS16 Transmit_PDO_Parameters_TPDO2_Event_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x14 */
UNS8 Transmit_PDO_Parameters_TRDO2_Mapping_Number = 0x0;		/* Mapped at index 0x2080, subindex 0x15 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_16 = 0x0;		/* Mapped at index 0x2080, subindex 0x16 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_17 = 0x0;		/* Mapped at index 0x2080, subindex 0x17 */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_1 = 0x0;		/* Mapped at index 0x2080, subindex 0x18 */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_2 = 0x0;		/* Mapped at index 0x2080, subindex 0x19 */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_3 = 0x0;		/* Mapped at index 0x2080, subindex 0x1A */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_4 = 0x0;		/* Mapped at index 0x2080, subindex 0x1B */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_5 = 0x0;		/* Mapped at index 0x2080, subindex 0x1C */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_6 = 0x0;		/* Mapped at index 0x2080, subindex 0x1D */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_7 = 0x0;		/* Mapped at index 0x2080, subindex 0x1E */
UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_8 = 0x0;		/* Mapped at index 0x2080, subindex 0x1F */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_20 = 0x0;		/* Mapped at index 0x2080, subindex 0x20 */
UNS32 Transmit_PDO_Parameters_TPDO3_COB_ID = 0x380;		/* Mapped at index 0x2080, subindex 0x21 */
UNS8 Transmit_PDO_Parameters_TPDO3_Transmission_Type = 0x0;		/* Mapped at index 0x2080, subindex 0x22 */
UNS32 Transmit_PDO_Parameters_TPDO3_Inhibit_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x23 */
UNS16 Transmit_PDO_Parameters_TPDO3_Event_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x24 */
UNS8 Transmit_PDO_Parameters_TRDO3_Mapping_Number = 0x0;		/* Mapped at index 0x2080, subindex 0x25 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_26 = 0x0;		/* Mapped at index 0x2080, subindex 0x26 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_27 = 0x0;		/* Mapped at index 0x2080, subindex 0x27 */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_1 = 0x0;		/* Mapped at index 0x2080, subindex 0x28 */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_2 = 0x0;		/* Mapped at index 0x2080, subindex 0x29 */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_3 = 0x0;		/* Mapped at index 0x2080, subindex 0x2A */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_4 = 0x0;		/* Mapped at index 0x2080, subindex 0x2B */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_5 = 0x0;		/* Mapped at index 0x2080, subindex 0x2C */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_6 = 0x0;		/* Mapped at index 0x2080, subindex 0x2D */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_7 = 0x0;		/* Mapped at index 0x2080, subindex 0x2E */
UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_8 = 0x0;		/* Mapped at index 0x2080, subindex 0x2F */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_30 = 0x0;		/* Mapped at index 0x2080, subindex 0x30 */
UNS32 Transmit_PDO_Parameters_TPDO4_COB_ID = 0x480;		/* Mapped at index 0x2080, subindex 0x31 */
UNS8 Transmit_PDO_Parameters_TPDO4_Transmission_Type = 0x0;		/* Mapped at index 0x2080, subindex 0x32 */
UNS32 Transmit_PDO_Parameters_TPDO4_Inhibit_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x33 */
UNS16 Transmit_PDO_Parameters_TPDO4_Event_Time = 0x0;		/* Mapped at index 0x2080, subindex 0x34 */
UNS8 Transmit_PDO_Parameters_TRDO4_Mapping_Number = 0x0;		/* Mapped at index 0x2080, subindex 0x35 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_36 = 0x0;		/* Mapped at index 0x2080, subindex 0x36 */
UNS8 Transmit_PDO_Parameters_Compatibility_Entry_37 = 0x0;		/* Mapped at index 0x2080, subindex 0x37 */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_1 = 0x0;		/* Mapped at index 0x2080, subindex 0x38 */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_2 = 0x0;		/* Mapped at index 0x2080, subindex 0x39 */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_3 = 0x0;		/* Mapped at index 0x2080, subindex 0x3A */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_4 = 0x0;		/* Mapped at index 0x2080, subindex 0x3B */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_5 = 0x0;		/* Mapped at index 0x2080, subindex 0x3C */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_6 = 0x0;		/* Mapped at index 0x2080, subindex 0x3D */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_7 = 0x0;		/* Mapped at index 0x2080, subindex 0x3E */
UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_8 = 0x0;		/* Mapped at index 0x2080, subindex 0x3F */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[5] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x12D;	/* 301 */
                    const CONSTSTORE subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), .pObject=(void*)&TestMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), .pObject=(void*)&TestMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t TestMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 TestMaster_highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1010_Save_Application_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1010_Save_Manufacturer_Parameters_1 }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 TestMaster_highestSubIndex_obj1011 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestMaster_obj1014 = 0x80;	/* 128 */
                    const CONSTSTORE subindex TestMaster_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1016[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1016[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1016[4] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestMaster_obj1017 = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    const CONSTSTORE subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 TestMaster_obj1281_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    const CONSTSTORE subindex TestMaster_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x80000400;	/* 2147484672 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1402_Event_Timer }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID_used_by_PDO = 0x80000500;	/* 2147484928 */
                    UNS8 TestMaster_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1403_Event_Timer }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1404_COB_ID_used_by_PDO = 0x80000200;	/* 2147484160 */
                    UNS8 TestMaster_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1405_COB_ID_used_by_PDO = 0x80000300;	/* 2147484416 */
                    UNS8 TestMaster_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1406_COB_ID_used_by_PDO = 0x80000400;	/* 2147484672 */
                    UNS8 TestMaster_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1407_COB_ID_used_by_PDO = 0x80000500;	/* 2147484928 */
                    UNS8 TestMaster_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaster_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1407_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1603[7] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1604 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1604[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1604[7] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1605 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1605[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1605[7] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1606 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1606[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1606[7] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1607 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1607[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1607[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1800_COB_ID_used_by_PDO = 0x80000180;	/* 2147484032 */
                    UNS8 TestMaster_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1801_COB_ID_used_by_PDO = 0x80000280;	/* 2147484288 */
                    UNS8 TestMaster_obj1801_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1802_COB_ID_used_by_PDO = 0xC0000380;	/* 3221226368 */
                    UNS8 TestMaster_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1802_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestMaster_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1803_COB_ID_used_by_PDO = 0xC0000480;	/* 3221226624 */
                    UNS8 TestMaster_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1803_Inhibit_Time = 0x3E8;	/* 1000 */
                    UNS8 TestMaster_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaster_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex TestMaster_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), .pObject=&TestMaster_obj1A03[7] }
                     };

/* index 0x1F22 :   Concise DCF. */
                    UNS8 TestMaster_highestSubIndex_obj1F22 = 2; /* number of subindex - 1*/
                    UNS8* TestMaster_obj1F22[] = 
                    {
                      "",
                      "\x01\x00\x00\x00\x17\x10\x00\x02\x00\x00\x00\xe8\x03"
                    };
                    const CONSTSTORE subindex TestMaster_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj1F22 },
                       { RW, domain, 0, .pObject=&TestMaster_obj1F22[0] },
                       { RW, domain, 13, .pObject=&TestMaster_obj1F22[1] }
                     };

/* index 0x2000 :   Mapped variable MasterMap1 */
                    ODCallback_t MasterMap1_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&MasterMap1 }
                     };

/* index 0x2001 :   Mapped variable MasterMap2 */
                    ODCallback_t MasterMap2_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&MasterMap2 }
                     };

/* index 0x2002 :   Mapped variable MasterMap3 */
                    ODCallback_t MasterMap3_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaster_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&MasterMap3 }
                     };

/* index 0x2003 :   Mapped variable MasterMap4 */
                    const CONSTSTORE subindex TestMaster_Index2003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&MasterMap4 }
                     };

/* index 0x2004 :   Mapped variable MasterMap5 */
                    const CONSTSTORE subindex TestMaster_Index2004[] = 
                     {
                       { RW, boolean, sizeof (UNS8), .pObject=&MasterMap5 }
                     };

/* index 0x2005 :   Mapped variable MasterMap6 */
                    const CONSTSTORE subindex TestMaster_Index2005[] = 
                     {
                       { RW, boolean, sizeof (UNS8), .pObject=&MasterMap6 }
                     };

/* index 0x2006 :   Mapped variable MasterMap7 */
                    const CONSTSTORE subindex TestMaster_Index2006[] = 
                     {
                       { RW, boolean, sizeof (UNS8), .pObject=&MasterMap7 }
                     };

/* index 0x2007 :   Mapped variable MasterMap8 */
                    const CONSTSTORE subindex TestMaster_Index2007[] = 
                     {
                       { RW, boolean, sizeof (UNS8), .pObject=&MasterMap8 }
                     };

/* index 0x2008 :   Mapped variable MasterMap9 */
                    const CONSTSTORE subindex TestMaster_Index2008[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&MasterMap9 }
                     };

/* index 0x2009 :   Mapped variable MasterMap10 */
                    const CONSTSTORE subindex TestMaster_Index2009[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&MasterMap10 }
                     };

/* index 0x200A :   Mapped variable MasterMap11 */
                    const CONSTSTORE subindex TestMaster_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&MasterMap11 }
                     };

/* index 0x200B :   Mapped variable MasterMap12 */
                    const CONSTSTORE subindex TestMaster_Index200B[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), .pObject=&MasterMap12 }
                     };

/* index 0x200C :   Mapped variable MasterMap13 */
                    const CONSTSTORE subindex TestMaster_Index200C[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), .pObject=&MasterMap13 }
                     };

/* index 0x2060 :   Mapped variable Communications Parameters */
                    UNS8 TestMaster_highestSubIndex_obj2060 = 8; /* number of subindex - 1*/
                    const CONSTSTORE subindex TestMaster_Index2060[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj2060 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Communications_Parameters_SYNC_COB_ID },
                       { RW, uint32, sizeof (UNS32), .pObject=&Communications_Parameters_Communication_Cycle_Period },
                       { RW, uint16, sizeof (UNS16), .pObject=&Communications_Parameters_Guard_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Communications_Parameters_Lift_Tiem_Factor },
                       { RW, uint32, sizeof (UNS32), .pObject=&Communications_Parameters_Emergency_COB_ID },
                       { RW, uint32, sizeof (UNS32), .pObject=&Communications_Parameters_Consumer_Heartbeat_Time },
                       { RW, uint16, sizeof (UNS16), .pObject=&Communications_Parameters_Producer_Heartbeat_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Communications_Parameters_Communication_Error }
                     };

/* index 0x2070 :   Mapped variable Recive PDO Parameters */
                    UNS8 TestMaster_highestSubIndex_obj2070 = 63; /* number of subindex - 1*/
                    const CONSTSTORE subindex TestMaster_Index2070[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj2070 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_RPDO1_Transmission_Type },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_PRDO1_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_04 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_05 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_06 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_07 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO1_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_10 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_RPDO2_Transmission_Type },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_PRDO2_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_14 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_15 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_16 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_17 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO2_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_20 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_RPDO3_Transmission_Type },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_PRDO3_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_24 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_25 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_26 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_27 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO3_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_30 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_RPDO4_Transmission_Type },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_PRDO4_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_34 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_35 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_36 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Recive_PDO_Parameters_Compatibility_Entry_37 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Recive_PDO_Parameters_RPDO4_Mapping_8 }
                     };

/* index 0x2080 :   Mapped variable Transmit PDO Parameters */
                    UNS8 TestMaster_highestSubIndex_obj2080 = 63; /* number of subindex - 1*/
                    const CONSTSTORE subindex TestMaster_Index2080[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaster_highestSubIndex_obj2080 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TPDO1_Transmission_Type },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), .pObject=&Transmit_PDO_Parameters_TPDO1_Event_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TRDO1_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_06 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_07 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO1_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_10 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TPDO2_Transmission_Type },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), .pObject=&Transmit_PDO_Parameters_TPDO2_Event_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TRDO2_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_16 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_17 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO2_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_20 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TPDO3_Transmission_Type },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), .pObject=&Transmit_PDO_Parameters_TPDO3_Event_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TRDO3_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_26 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_27 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO3_Mapping_8 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_30 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_COB_ID },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TPDO4_Transmission_Type },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), .pObject=&Transmit_PDO_Parameters_TPDO4_Event_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_TRDO4_Mapping_Number },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_36 },
                       { RW, uint8, sizeof (UNS8), .pObject=&Transmit_PDO_Parameters_Compatibility_Entry_37 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_1 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_2 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_3 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_4 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_5 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_6 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_7 },
                       { RW, uint32, sizeof (UNS32), .pObject=&Transmit_PDO_Parameters_TPDO4_Mapping_8 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const CONSTSTORE indextable TestMaster_objdict[] = 
{
  { (const CONSTSTORE subindex* const)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (const CONSTSTORE subindex* const)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (const CONSTSTORE subindex* const)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (const CONSTSTORE subindex* const)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (const CONSTSTORE subindex* const)TestMaster_Index1010,sizeof(TestMaster_Index1010)/sizeof(TestMaster_Index1010[0]), 0x1010},
  { (const CONSTSTORE subindex* const)TestMaster_Index1011,sizeof(TestMaster_Index1011)/sizeof(TestMaster_Index1011[0]), 0x1011},
  { (const CONSTSTORE subindex* const)TestMaster_Index1014,sizeof(TestMaster_Index1014)/sizeof(TestMaster_Index1014[0]), 0x1014},
  { (const CONSTSTORE subindex* const)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (const CONSTSTORE subindex* const)TestMaster_Index1017,sizeof(TestMaster_Index1017)/sizeof(TestMaster_Index1017[0]), 0x1017},
  { (const CONSTSTORE subindex* const)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (const CONSTSTORE subindex* const)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (const CONSTSTORE subindex* const)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},
  { (const CONSTSTORE subindex* const)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (const CONSTSTORE subindex* const)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (const CONSTSTORE subindex* const)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (const CONSTSTORE subindex* const)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
  { (const CONSTSTORE subindex* const)TestMaster_Index1404,sizeof(TestMaster_Index1404)/sizeof(TestMaster_Index1404[0]), 0x1404},
  { (const CONSTSTORE subindex* const)TestMaster_Index1405,sizeof(TestMaster_Index1405)/sizeof(TestMaster_Index1405[0]), 0x1405},
  { (const CONSTSTORE subindex* const)TestMaster_Index1406,sizeof(TestMaster_Index1406)/sizeof(TestMaster_Index1406[0]), 0x1406},
  { (const CONSTSTORE subindex* const)TestMaster_Index1407,sizeof(TestMaster_Index1407)/sizeof(TestMaster_Index1407[0]), 0x1407},
  { (const CONSTSTORE subindex* const)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (const CONSTSTORE subindex* const)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (const CONSTSTORE subindex* const)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (const CONSTSTORE subindex* const)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},
  { (const CONSTSTORE subindex* const)TestMaster_Index1604,sizeof(TestMaster_Index1604)/sizeof(TestMaster_Index1604[0]), 0x1604},
  { (const CONSTSTORE subindex* const)TestMaster_Index1605,sizeof(TestMaster_Index1605)/sizeof(TestMaster_Index1605[0]), 0x1605},
  { (const CONSTSTORE subindex* const)TestMaster_Index1606,sizeof(TestMaster_Index1606)/sizeof(TestMaster_Index1606[0]), 0x1606},
  { (const CONSTSTORE subindex* const)TestMaster_Index1607,sizeof(TestMaster_Index1607)/sizeof(TestMaster_Index1607[0]), 0x1607},
  { (const CONSTSTORE subindex* const)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
  { (const CONSTSTORE subindex* const)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
  { (const CONSTSTORE subindex* const)TestMaster_Index1802,sizeof(TestMaster_Index1802)/sizeof(TestMaster_Index1802[0]), 0x1802},
  { (const CONSTSTORE subindex* const)TestMaster_Index1803,sizeof(TestMaster_Index1803)/sizeof(TestMaster_Index1803[0]), 0x1803},
  { (const CONSTSTORE subindex* const)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
  { (const CONSTSTORE subindex* const)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
  { (const CONSTSTORE subindex* const)TestMaster_Index1A02,sizeof(TestMaster_Index1A02)/sizeof(TestMaster_Index1A02[0]), 0x1A02},
  { (const CONSTSTORE subindex* const)TestMaster_Index1A03,sizeof(TestMaster_Index1A03)/sizeof(TestMaster_Index1A03[0]), 0x1A03},
  { (const CONSTSTORE subindex* const)TestMaster_Index1F22,sizeof(TestMaster_Index1F22)/sizeof(TestMaster_Index1F22[0]), 0x1F22},
  { (const CONSTSTORE subindex* const)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (const CONSTSTORE subindex* const)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (const CONSTSTORE subindex* const)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (const CONSTSTORE subindex* const)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (const CONSTSTORE subindex* const)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (const CONSTSTORE subindex* const)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (const CONSTSTORE subindex* const)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (const CONSTSTORE subindex* const)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
  { (const CONSTSTORE subindex* const)TestMaster_Index2008,sizeof(TestMaster_Index2008)/sizeof(TestMaster_Index2008[0]), 0x2008},
  { (const CONSTSTORE subindex* const)TestMaster_Index2009,sizeof(TestMaster_Index2009)/sizeof(TestMaster_Index2009[0]), 0x2009},
  { (const CONSTSTORE subindex* const)TestMaster_Index200A,sizeof(TestMaster_Index200A)/sizeof(TestMaster_Index200A[0]), 0x200A},
  { (const CONSTSTORE subindex* const)TestMaster_Index200B,sizeof(TestMaster_Index200B)/sizeof(TestMaster_Index200B[0]), 0x200B},
  { (const CONSTSTORE subindex* const)TestMaster_Index200C,sizeof(TestMaster_Index200C)/sizeof(TestMaster_Index200C[0]), 0x200C},
  { (const CONSTSTORE subindex* const)TestMaster_Index2060,sizeof(TestMaster_Index2060)/sizeof(TestMaster_Index2060[0]), 0x2060},
  { (const CONSTSTORE subindex* const)TestMaster_Index2070,sizeof(TestMaster_Index2070)/sizeof(TestMaster_Index2070[0]), 0x2070},
  { (const CONSTSTORE subindex* const)TestMaster_Index2080,sizeof(TestMaster_Index2080)/sizeof(TestMaster_Index2080[0]), 0x2080},
};

const CONSTSTORE indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = TestMaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = TestMaster_Index1006_callbacks; break;
		case 0x1010: i = 4;break;
		case 0x1011: i = 5;break;
		case 0x1014: i = 6;break;
		case 0x1016: i = 7;break;
		case 0x1017: i = 8;*callbacks = TestMaster_Index1017_callbacks; break;
		case 0x1018: i = 9;break;
		case 0x1280: i = 10;break;
		case 0x1281: i = 11;break;
		case 0x1400: i = 12;break;
		case 0x1401: i = 13;break;
		case 0x1402: i = 14;break;
		case 0x1403: i = 15;break;
		case 0x1404: i = 16;break;
		case 0x1405: i = 17;break;
		case 0x1406: i = 18;break;
		case 0x1407: i = 19;break;
		case 0x1600: i = 20;break;
		case 0x1601: i = 21;break;
		case 0x1602: i = 22;break;
		case 0x1603: i = 23;break;
		case 0x1604: i = 24;break;
		case 0x1605: i = 25;break;
		case 0x1606: i = 26;break;
		case 0x1607: i = 27;break;
		case 0x1800: i = 28;*callbacks = TestMaster_Index1800_callbacks; break;
		case 0x1801: i = 29;*callbacks = TestMaster_Index1801_callbacks; break;
		case 0x1802: i = 30;*callbacks = TestMaster_Index1802_callbacks; break;
		case 0x1803: i = 31;*callbacks = TestMaster_Index1803_callbacks; break;
		case 0x1A00: i = 32;break;
		case 0x1A01: i = 33;break;
		case 0x1A02: i = 34;break;
		case 0x1A03: i = 35;break;
		case 0x1F22: i = 36;break;
		case 0x2000: i = 37;*callbacks = MasterMap1_callbacks; break;
		case 0x2001: i = 38;*callbacks = MasterMap2_callbacks; break;
		case 0x2002: i = 39;*callbacks = MasterMap3_callbacks; break;
		case 0x2003: i = 40;break;
		case 0x2004: i = 41;break;
		case 0x2005: i = 42;break;
		case 0x2006: i = 43;break;
		case 0x2007: i = 44;break;
		case 0x2008: i = 45;break;
		case 0x2009: i = 46;break;
		case 0x200A: i = 47;break;
		case 0x200B: i = 48;break;
		case 0x200C: i = 49;break;
		case 0x2060: i = 50;break;
		case 0x2070: i = 51;break;
		case 0x2080: i = 52;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const CONSTSTORE quick_index TestMaster_firstIndex = {
  0, /* SDO_SVR */
  10, /* SDO_CLT */
  12, /* PDO_RCV */
  20, /* PDO_RCV_MAP */
  28, /* PDO_TRS */
  32 /* PDO_TRS_MAP */
};

const CONSTSTORE quick_index TestMaster_lastIndex = {
  0, /* SDO_SVR */
  11, /* SDO_CLT */
  19, /* PDO_RCV */
  27, /* PDO_RCV_MAP */
  31, /* PDO_TRS */
  35 /* PDO_TRS_MAP */
};

const CONSTSTORE UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

