
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS32 MasterMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 MasterMap2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 MasterMap3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 MasterMap4;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 MasterMap5;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 MasterMap6;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS8 MasterMap7;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS8 MasterMap8;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS8 MasterMap9;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS32 MasterMap10;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 MasterMap11;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 MasterMap12;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER16 MasterMap13;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS32 Communications_Parameters_SYNC_COB_ID;		/* Mapped at index 0x2060, subindex 0x01 */
extern UNS32 Communications_Parameters_Communication_Cycle_Period;		/* Mapped at index 0x2060, subindex 0x02 */
extern UNS16 Communications_Parameters_Guard_Time;		/* Mapped at index 0x2060, subindex 0x03 */
extern UNS8 Communications_Parameters_Lift_Tiem_Factor;		/* Mapped at index 0x2060, subindex 0x04 */
extern UNS32 Communications_Parameters_Emergency_COB_ID;		/* Mapped at index 0x2060, subindex 0x05 */
extern UNS32 Communications_Parameters_Consumer_Heartbeat_Time;		/* Mapped at index 0x2060, subindex 0x06 */
extern UNS16 Communications_Parameters_Producer_Heartbeat_Time;		/* Mapped at index 0x2060, subindex 0x07 */
extern UNS8 Communications_Parameters_Communication_Error;		/* Mapped at index 0x2060, subindex 0x08 */
extern UNS32 Recive_PDO_Parameters_RPDO1_COB_ID;		/* Mapped at index 0x2070, subindex 0x01 */
extern UNS8 Recive_PDO_Parameters_RPDO1_Transmission_Type;		/* Mapped at index 0x2070, subindex 0x02 */
extern UNS8 Recive_PDO_Parameters_PRDO1_Mapping_Number;		/* Mapped at index 0x2070, subindex 0x03 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_04;		/* Mapped at index 0x2070, subindex 0x04 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_05;		/* Mapped at index 0x2070, subindex 0x05 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_06;		/* Mapped at index 0x2070, subindex 0x06 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_07;		/* Mapped at index 0x2070, subindex 0x07 */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_1;		/* Mapped at index 0x2070, subindex 0x08 */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_2;		/* Mapped at index 0x2070, subindex 0x09 */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_3;		/* Mapped at index 0x2070, subindex 0x0A */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_4;		/* Mapped at index 0x2070, subindex 0x0B */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_5;		/* Mapped at index 0x2070, subindex 0x0C */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_6;		/* Mapped at index 0x2070, subindex 0x0D */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_7;		/* Mapped at index 0x2070, subindex 0x0E */
extern UNS32 Recive_PDO_Parameters_RPDO1_Mapping_8;		/* Mapped at index 0x2070, subindex 0x0F */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_10;		/* Mapped at index 0x2070, subindex 0x10 */
extern UNS32 Recive_PDO_Parameters_RPDO2_COB_ID;		/* Mapped at index 0x2070, subindex 0x11 */
extern UNS8 Recive_PDO_Parameters_RPDO2_Transmission_Type;		/* Mapped at index 0x2070, subindex 0x12 */
extern UNS8 Recive_PDO_Parameters_PRDO2_Mapping_Number;		/* Mapped at index 0x2070, subindex 0x13 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_14;		/* Mapped at index 0x2070, subindex 0x14 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_15;		/* Mapped at index 0x2070, subindex 0x15 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_16;		/* Mapped at index 0x2070, subindex 0x16 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_17;		/* Mapped at index 0x2070, subindex 0x17 */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_1;		/* Mapped at index 0x2070, subindex 0x18 */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_2;		/* Mapped at index 0x2070, subindex 0x19 */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_3;		/* Mapped at index 0x2070, subindex 0x1A */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_4;		/* Mapped at index 0x2070, subindex 0x1B */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_5;		/* Mapped at index 0x2070, subindex 0x1C */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_6;		/* Mapped at index 0x2070, subindex 0x1D */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_7;		/* Mapped at index 0x2070, subindex 0x1E */
extern UNS32 Recive_PDO_Parameters_RPDO2_Mapping_8;		/* Mapped at index 0x2070, subindex 0x1F */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_20;		/* Mapped at index 0x2070, subindex 0x20 */
extern UNS32 Recive_PDO_Parameters_RPDO3_COB_ID;		/* Mapped at index 0x2070, subindex 0x21 */
extern UNS8 Recive_PDO_Parameters_RPDO3_Transmission_Type;		/* Mapped at index 0x2070, subindex 0x22 */
extern UNS8 Recive_PDO_Parameters_PRDO3_Mapping_Number;		/* Mapped at index 0x2070, subindex 0x23 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_24;		/* Mapped at index 0x2070, subindex 0x24 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_25;		/* Mapped at index 0x2070, subindex 0x25 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_26;		/* Mapped at index 0x2070, subindex 0x26 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_27;		/* Mapped at index 0x2070, subindex 0x27 */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_1;		/* Mapped at index 0x2070, subindex 0x28 */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_2;		/* Mapped at index 0x2070, subindex 0x29 */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_3;		/* Mapped at index 0x2070, subindex 0x2A */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_4;		/* Mapped at index 0x2070, subindex 0x2B */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_5;		/* Mapped at index 0x2070, subindex 0x2C */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_6;		/* Mapped at index 0x2070, subindex 0x2D */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_7;		/* Mapped at index 0x2070, subindex 0x2E */
extern UNS32 Recive_PDO_Parameters_RPDO3_Mapping_8;		/* Mapped at index 0x2070, subindex 0x2F */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_30;		/* Mapped at index 0x2070, subindex 0x30 */
extern UNS32 Recive_PDO_Parameters_RPDO4_COB_ID;		/* Mapped at index 0x2070, subindex 0x31 */
extern UNS8 Recive_PDO_Parameters_RPDO4_Transmission_Type;		/* Mapped at index 0x2070, subindex 0x32 */
extern UNS8 Recive_PDO_Parameters_PRDO4_Mapping_Number;		/* Mapped at index 0x2070, subindex 0x33 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_34;		/* Mapped at index 0x2070, subindex 0x34 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_35;		/* Mapped at index 0x2070, subindex 0x35 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_36;		/* Mapped at index 0x2070, subindex 0x36 */
extern UNS8 Recive_PDO_Parameters_Compatibility_Entry_37;		/* Mapped at index 0x2070, subindex 0x37 */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_1;		/* Mapped at index 0x2070, subindex 0x38 */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_2;		/* Mapped at index 0x2070, subindex 0x39 */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_3;		/* Mapped at index 0x2070, subindex 0x3A */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_4;		/* Mapped at index 0x2070, subindex 0x3B */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_5;		/* Mapped at index 0x2070, subindex 0x3C */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_6;		/* Mapped at index 0x2070, subindex 0x3D */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_7;		/* Mapped at index 0x2070, subindex 0x3E */
extern UNS32 Recive_PDO_Parameters_RPDO4_Mapping_8;		/* Mapped at index 0x2070, subindex 0x3F */
extern UNS32 Transmit_PDO_Parameters_TPDO1_COB_ID;		/* Mapped at index 0x2080, subindex 0x01 */
extern UNS8 Transmit_PDO_Parameters_TPDO1_Transmission_Type;		/* Mapped at index 0x2080, subindex 0x02 */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Inhibit_Time;		/* Mapped at index 0x2080, subindex 0x03 */
extern UNS16 Transmit_PDO_Parameters_TPDO1_Event_Time;		/* Mapped at index 0x2080, subindex 0x04 */
extern UNS8 Transmit_PDO_Parameters_TRDO1_Mapping_Number;		/* Mapped at index 0x2080, subindex 0x05 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_06;		/* Mapped at index 0x2080, subindex 0x06 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_07;		/* Mapped at index 0x2080, subindex 0x07 */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_1;		/* Mapped at index 0x2080, subindex 0x08 */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_2;		/* Mapped at index 0x2080, subindex 0x09 */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_3;		/* Mapped at index 0x2080, subindex 0x0A */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_4;		/* Mapped at index 0x2080, subindex 0x0B */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_5;		/* Mapped at index 0x2080, subindex 0x0C */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_6;		/* Mapped at index 0x2080, subindex 0x0D */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_7;		/* Mapped at index 0x2080, subindex 0x0E */
extern UNS32 Transmit_PDO_Parameters_TPDO1_Mapping_8;		/* Mapped at index 0x2080, subindex 0x0F */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_10;		/* Mapped at index 0x2080, subindex 0x10 */
extern UNS32 Transmit_PDO_Parameters_TPDO2_COB_ID;		/* Mapped at index 0x2080, subindex 0x11 */
extern UNS8 Transmit_PDO_Parameters_TPDO2_Transmission_Type;		/* Mapped at index 0x2080, subindex 0x12 */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Inhibit_Time;		/* Mapped at index 0x2080, subindex 0x13 */
extern UNS16 Transmit_PDO_Parameters_TPDO2_Event_Time;		/* Mapped at index 0x2080, subindex 0x14 */
extern UNS8 Transmit_PDO_Parameters_TRDO2_Mapping_Number;		/* Mapped at index 0x2080, subindex 0x15 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_16;		/* Mapped at index 0x2080, subindex 0x16 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_17;		/* Mapped at index 0x2080, subindex 0x17 */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_1;		/* Mapped at index 0x2080, subindex 0x18 */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_2;		/* Mapped at index 0x2080, subindex 0x19 */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_3;		/* Mapped at index 0x2080, subindex 0x1A */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_4;		/* Mapped at index 0x2080, subindex 0x1B */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_5;		/* Mapped at index 0x2080, subindex 0x1C */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_6;		/* Mapped at index 0x2080, subindex 0x1D */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_7;		/* Mapped at index 0x2080, subindex 0x1E */
extern UNS32 Transmit_PDO_Parameters_TPDO2_Mapping_8;		/* Mapped at index 0x2080, subindex 0x1F */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_20;		/* Mapped at index 0x2080, subindex 0x20 */
extern UNS32 Transmit_PDO_Parameters_TPDO3_COB_ID;		/* Mapped at index 0x2080, subindex 0x21 */
extern UNS8 Transmit_PDO_Parameters_TPDO3_Transmission_Type;		/* Mapped at index 0x2080, subindex 0x22 */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Inhibit_Time;		/* Mapped at index 0x2080, subindex 0x23 */
extern UNS16 Transmit_PDO_Parameters_TPDO3_Event_Time;		/* Mapped at index 0x2080, subindex 0x24 */
extern UNS8 Transmit_PDO_Parameters_TRDO3_Mapping_Number;		/* Mapped at index 0x2080, subindex 0x25 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_26;		/* Mapped at index 0x2080, subindex 0x26 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_27;		/* Mapped at index 0x2080, subindex 0x27 */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_1;		/* Mapped at index 0x2080, subindex 0x28 */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_2;		/* Mapped at index 0x2080, subindex 0x29 */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_3;		/* Mapped at index 0x2080, subindex 0x2A */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_4;		/* Mapped at index 0x2080, subindex 0x2B */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_5;		/* Mapped at index 0x2080, subindex 0x2C */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_6;		/* Mapped at index 0x2080, subindex 0x2D */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_7;		/* Mapped at index 0x2080, subindex 0x2E */
extern UNS32 Transmit_PDO_Parameters_TPDO3_Mapping_8;		/* Mapped at index 0x2080, subindex 0x2F */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_30;		/* Mapped at index 0x2080, subindex 0x30 */
extern UNS32 Transmit_PDO_Parameters_TPDO4_COB_ID;		/* Mapped at index 0x2080, subindex 0x31 */
extern UNS8 Transmit_PDO_Parameters_TPDO4_Transmission_Type;		/* Mapped at index 0x2080, subindex 0x32 */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Inhibit_Time;		/* Mapped at index 0x2080, subindex 0x33 */
extern UNS16 Transmit_PDO_Parameters_TPDO4_Event_Time;		/* Mapped at index 0x2080, subindex 0x34 */
extern UNS8 Transmit_PDO_Parameters_TRDO4_Mapping_Number;		/* Mapped at index 0x2080, subindex 0x35 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_36;		/* Mapped at index 0x2080, subindex 0x36 */
extern UNS8 Transmit_PDO_Parameters_Compatibility_Entry_37;		/* Mapped at index 0x2080, subindex 0x37 */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_1;		/* Mapped at index 0x2080, subindex 0x38 */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_2;		/* Mapped at index 0x2080, subindex 0x39 */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_3;		/* Mapped at index 0x2080, subindex 0x3A */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_4;		/* Mapped at index 0x2080, subindex 0x3B */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_5;		/* Mapped at index 0x2080, subindex 0x3C */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_6;		/* Mapped at index 0x2080, subindex 0x3D */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_7;		/* Mapped at index 0x2080, subindex 0x3E */
extern UNS32 Transmit_PDO_Parameters_TPDO4_Mapping_8;		/* Mapped at index 0x2080, subindex 0x3F */

#endif // TESTMASTER_H
