
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_TEST_H
#define MASTER_TEST_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_test_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_test_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data master_test_Data;

#endif // MASTER_TEST_H
